name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      # - name: Login to AWS
      #   run: |
      #     aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws configure set region ${{ secrets.REGION }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: test suite
        run: npm run test

      - name: Build React app
        run: npm run build

      # - name: Upload package to S3 bucket
      #   run: |
      #     aws s3 sync build/ "${{ secrets.BUILD_PATH }}" --delete --cache-control "public, max-age=604800, immutable"
